---
##################################################
# 🗄️ ClusterSecretStore - Secret Backend         #
##################################################
# ➡️ ESO config to use OpenBao via eso-openbao SA
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: openbao
spec:
  provider:
    vault:
      server: https://openbao.islandbytes.net:8200
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes   # OpenBao auth mount path
          role: eso               # OpenBao role name
          serviceAccountRef:
            name: eso-openbao
            namespace: external-secrets