---
##################################################
# 🚀 HelmRelease - Chart Deployment Spec        #
##################################################
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  chart:
    spec:
      chart: external-secrets
      version: 1.1.1
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: external-secrets
  valuesFrom:
  - kind: ConfigMap
    name: helm-values-override-external-secrets
    valuesKey: values.yaml
