---
##########################################
# 🚀 HelmRelease - Chart Deployment Spec #
##########################################
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: reflector
spec:
  chart:
    spec:
      chart: reflector
      version: 9.1.45
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: reflector
  valuesFrom:
  - kind: ConfigMap
    name: helm-values-override-reflector
    valuesKey: values.yaml
