---
#############################################
# 🔐 ExternalSecret - External Secret Spec  #
#############################################
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-secret  
  namespace: longhorn-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao                     # your existing ClusterSecretStore
  target:
    name: garage-secret               # the K8s Secret that apps will consume
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  dataFrom:
    - extract:
        key: k8s/infra_apps/longhorn/garage-secret
