apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: demo-app
  namespace: external-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: demo-app-secret
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: USERNAME
      remoteRef:
        key: demo/app         # -> vault: kv/data/demo/app
        property: username
    - secretKey: PASSWORD
      remoteRef:
        key: demo/app
        property: password
